config/routes.rb
Rails.application.routes.draw do
  root to: 'groups#index'
  resources :groups, except: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :memberships, dependent: :delete_all
  has_many :users, through: :memberships

  accepts_nested_attributes_for :memberships, allow_destroy: true

  validates :name, presence: true, uniqueness: true
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :user, :group, presence: true
  validates :user_id, uniqueness: {scope: [:group_id]}
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update, :destroy]
  before_action :set_users, only: [:new, :create, :edit, :update]

  def index
    @groups = Group.order(name: :asc).includes(:users).load
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)

    if @group.save
      redirect_to root_url, notice: "Group created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to root_url, notice: "Group updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @group.destroy
    redirect_to root_url, notice: "Group deleted."
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def set_users
    @users = User.order(name: :asc)
  end

  def group_params
    params.require(:group).permit(:name, memberships_attributes: [:user_id, :id, :_destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |f| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :users %>

    <% users.each do |user| %>
      <% membership = group.memberships.find { |membership| membership.user_id == user.id } %>
      <% membership ||= Membership.new(group: group, user: user).tap(&:mark_for_destruction) %>

      <%= f.fields_for :memberships, membership do |membership_fields| %>
        <%= membership_fields.hidden_field :user_id %>

        <div class="field">
          <%= membership_fields.label :_destroy do %>
            <%= membership_fields.check_box :_destroy, {checked: !membership.marked_for_destruction?}, "0", "1" %>
            <%= user.name %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Update Group</h1>

<p>
  <%= link_to "Back to Groups", root_url %>
</p>

<%= render "form", group: @group, users: @users %>

app/views/groups/index.html.erb
<h1>Groups</h1>

<% if @groups.any? %>
  <p><%= link_to "Create Group", new_group_path %></p>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Members</th>
        <th colspan="2">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @groups.each do |group| %>
        <tr>
          <td><%= group.name %></td>
          <td><%= group.users.map(&:name).sort.join(", ") %></td>
          <td><%= link_to "Edit", edit_group_path(group) %></td>
          <td><%= link_to "Delete", group_path(group), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>There are no Groups yet. <%= link_to "Create", new_group_path %> one!</p>
<% end %>

app/views/groups/new.html.erb
<h1>Create Group</h1>

<p>
  <%= link_to "Back to Groups", root_url %>
</p>

<%= render "form", group: @group, users: @users %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HasManyThroughSelection</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="turbo-refresh-method" content="morph">
    <meta name="turbo-prefetch" content="false">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p style="color: green"><%= notice %></p>
    <%= yield %>
  </body>
</html>